config/routes.rb
Rails.application.routes.draw do
  resources :users, except: :index do
    resources :messages, only: :create

    collection do
      get 'complete_sign_up'
      get 'verify_email'
      patch 'update_email'
    end

    member do
      get 'email_confirmed'
      get 'personal_messages'
      post 'join_group'
    end
  end

  resources :groups, only: [:show] do
    delete 'drop_user', on: :member
    resources :drop_user_votes, only: [:create, :destroy]
    resources :expand_group_votes, only: [:create, :destroy]
    resources :topics, shallow: true, only: [:show, :create] do
      resources :messages, only: :create
      get 'change', on: :member
    end
    resources :activities, shallow: true, except: [:index] do
      resources :messages, only: [:create, :index]
      member do
        post 'add_user'
        delete 'remove_user'
      end
    end
  end

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/get_started')
  delete 'logout' => 'sessions#destroy'
  post 'login' => 'sessions#login'

  resources :password_resets, except: [:get, :destroy]
  resources :newsletters, only: [:new, :create]
  resources :surveys, only: [:new, :create]

  get "get_started" => "home#landing"
  get "admin_dash" => "home#admin_dash"
  get "faq" => "home#faq"
  get "about" => "home#about"
  get "privacy_policy" => "home#privacy_policy"
  get "terms_of_service" => "home#terms_of_service"
  root 'users#show'

  namespace :api do
    namespace :v1 do
      resources :users, only: [:show, :update, :create] do
        resources :groups, only: [:index]
        member do
          get 'personal_messages'
          post 'add_group'
        end
      end

      resources :groups, only: :show do
        delete 'drop_user', on: :member
        resources :activities, only: [:create, :update, :show] do
          member do
            post 'add_user'
            delete 'remove_user'
          end
        end
      end


      resources :messages, only: :create
      resources :sessions, only: [:create, :destroy]
    end
  end

  get "*any", via: :all, to: "errors#not_found"
end

app/models/group.rb
class Group < ActiveRecord::Base
	extend FriendlyId
	include Sluggable
	friendly_id :slug_candidates, use: :slugged

	has_many :user_groups
	has_many :users, through: :user_groups
	has_many :messages, as: :messageable
	has_many :topics, dependent: :destroy
	has_many :notifications, as: :notifiable, dependent: :destroy
	has_many :activities, dependent: :destroy
	has_many :drop_user_votes, dependent: :destroy
	has_many :expand_group_votes, dependent: :destroy

	reverse_geocoded_by :latitude, :longitude

	after_create :create_general_topic

	delegate :size, to: :expand_group_votes, prefix: true
	delegate :attended_activities_count, :future_activities, to: :activities
	delegate :count, :empty?, :include?, to: :users, prefix: true
	delegate :ids, to: :topics, prefix: true

	scope :open_groups, -> { where(can_join: true) }
	scope :category_groups, ->(category) { where(category: category) }
	scope :non_former_groups, ->(group_ids) { where.not(id: group_ids) }
	scope :same_age, ->(age_group) { where(age_group: age_group) }
	scope :degree_groups, ->(degree) { where(degree: degree) }
	scope :ready_groups, -> { where(ready_to_expand: true) }

	def self.search(params)
		self.open_groups.category_groups(params[:category]).same_age(params[:age_group]).degree_groups(1).near([params[:latitude], params[:longitude]], 0.5).order(created_at: :asc).non_former_groups(params[:group_ids])[0]
	end

	def city
	  users.first.city
	end

	def name_group
		self.name = GroupNameHelper.name.sample
	end

	private
	def create_general_topic
	  self.topics.create(name: "General")
	end
end

app/controllers/api/v1/groups_controller.rb
class Api::V1::GroupsController < ApiController
  respond_to :json
  before_action :set_group, except: :index

  def show
    render json: @group
  end

  def index
    render json: User.friendly.find(params[:user_id]).groups
  end

  def drop_user
    DropUser.new(@group, current_user).drop
    head 204
  end

  private
  def set_group
    @group = Group.friendly.find(params[:id])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	def show
		group = Group.friendly.find(params[:id])
		authorize! :read, group
		@group_show = GroupShow.new(group, current_user, params[:page])

		current_user.dismiss_group_notifications_from_group(group)
	end

	def drop_user
		@group = Group.friendly.find(params[:id])
		authorize! :read, @group

		DropUser.new(@group, current_user).drop
		redirect_to root_path
	end
end

app/views/groups/_buttons.html.erb
<%= link_to "Leave Group", drop_user_group_path(@group_show.group), method: :delete, class: 'btn red white-text', data: @group_show.delete_confirm_message %>

<% if @group_show.ripe_for_expansion? %>
  <% unless @group_show.user_expand_group_votes(current_user) %>
    <%= link_to "Expand Group #{@group_show.expand_group_votes_size}/#{@group_show.users_count}", group_expand_group_votes_path(@group_show.group), method: :post, class: 'waves-effect btn deep-orange white-text expand', remote: @group_show.not_almost_expandable? %>
  <% else %>
    <%= link_to "Don't Expand #{@group_show.expand_group_votes_size}/#{@group_show.users_count}", group_expand_group_vote_path(@group_show.group, @group_show.user_expand_group_votes(current_user)), method: :delete, class: 'waves-effect btn brown white-text remain', remote: true %>
  <% end %>
<% end %>


<a href="#members" class="waves-effect btn pink modal-trigger white-text">Members (<%= @group_show.users_count %>)</a>
<% unless @group_show.one_user? %>
  <a href="#new-topic" class="waves-effect btn indigo modal-trigger white-text">New Thread</a>
<% end %>

app/views/groups/show.html.erb
<div class="row group-page">
	<div class="col s12">
		<h3>
			<u><%= @group_show.group_name %></u>
		</h3>
		<div class="hide-on-med-and-down">
			<%= render "groups/buttons" %>

			<%= link_to "Propose Activity", new_group_activity_path(@group_show.group), id: 'new_activity', class: 'waves-effect waves-light btn purple white-text', remote: true %>
		</div>
	</div>

	<div class="col s12 l9">
		<% if @group_show.one_user? %>
		<div class="card-panel">
			<h4>You don't have anyone in your group <i>yet</i>.</h4>
			<p>You'll get an email notification when your group is complete. We're working hard to get people in your area to join, so hang tight. Please help us out by liking us on social media. The faster we add users, the faster your group will fill up.</p>
			<div class="center-align">
				<a href="https://www.facebook.com/gokrewe" target="_blank"><%= image_tag "facebook" %></a>
				<a href="https://twitter.com/gokrewe" target="_blank" ><%= image_tag "twitter" %></a>
			</div>
		</div>

		<% else %>
		<h4 class='hide-on-med-and-down'>Messages</h4>
			<div class="topics">
				<%= render partial: 'topics/topics', locals: { topics: @group_show.topics } %>
			</div>
			<%= render partial: 'topics/new', locals: { group: @group_show.group, topic: @group_show.new_topic } %>

		<div class="message-group">
			<%= render partial: 'topics/topic', locals: { topic: @group_show.topic } %>
		</div>
		<% end %>
	</div>

	<div class="col s12 m3 hide-on-med-and-down">
		<%= render partial: "activities/activities", locals: { activities: @group_show.activities, group: @group_show.group, user_show: false } %>
	</div>

	<div id='new-activity' class="modal"></div>

	<div class="modal" id="activities">
		<div class="modal-content">

			<%= render partial: "activities/activities", locals: { activities: @group_show.activities, group: @group_show.group, user_show: false } %>
		</div>
	</div>

	<div class="modal bottom-sheet" id="members">
		<div class="modal-content">
			<h4>Members</h4>
			<ul class="collection">
				<% if @group_show.one_user? %>
					<li class="collection-item no-users">No other users in the group yet. We'll let you know when they join.</li>
				<% end %>
				<% @group_show.users.each do |user| %>
					<li class="collection-item avatar">
						<%= image_tag user.photo_url || avatar_url(user), class: "circle" %>
						<span class="title"><%= link_to user.name, personal_messages_user_path(user) %></span>

						 <% if @group_show.primary_group? %>
							 	<% if current_user.can_vote?(user) %>
							 		<%= link_to "Remove from group #{user.group_drop_votes_count(@group_show.group)}/3", group_drop_user_votes_path(@group_show.group, user_id: user), remote: true, method: :post, class: 'btn red', id: "remove-btn-#{user.id}", data: {confirm: "Vote to remove this user?", text: "Remove inactive users, but only if they're inactive."} %>
							 	<% elsif current_user.can_unvote?(user) %>
							 		<%= link_to "Undo #{user.group_drop_votes_count(@group_show.group)}/3", group_drop_user_vote_path(@group_show.group, user.voter_vote(current_user)), remote: true, method: :delete, class: 'btn orange', id: "undo-btn-#{user.id}" %>
							 	<% end %>
						 <% end %>
					 	</li>
				<% end %>
			</ul>
		</div>
	</div>
</div>

app/views/groups/show.js.erb
$('.next-topic').replaceWith('<%= j render partial: "topics/topics", locals: { topics: @group_show.topics}  %>')
<% unless @group_show.next_page %>
  $('.next-topic').remove();
<% end %>

$('.topics').animate({ scrollLeft: $('.topics')[0].scrollWidth }, 1000)
Formatter.highlightTopic()