config/routes.rb
Rails.application.routes.draw do
  resources :users, except: :index do
    resources :messages, only: :create

    collection do
      get 'complete_sign_up'
      get 'verify_email'
      patch 'update_email'
    end

    member do
      get 'email_confirmed'
      get 'personal_messages'
      post 'join_group'
    end
  end

  resources :groups, only: [:show] do
    delete 'drop_user', on: :member
    resources :drop_user_votes, only: [:create, :destroy]
    resources :expand_group_votes, only: [:create, :destroy]
    resources :topics, shallow: true, only: [:show, :create] do
      resources :messages, only: :create
      get 'change', on: :member
    end
    resources :activities, shallow: true, except: [:index] do
      resources :messages, only: [:create, :index]
      member do
        post 'add_user'
        delete 'remove_user'
      end
    end
  end

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/get_started')
  delete 'logout' => 'sessions#destroy'
  post 'login' => 'sessions#login'

  resources :password_resets, except: [:get, :destroy]
  resources :newsletters, only: [:new, :create]
  resources :surveys, only: [:new, :create]

  get "get_started" => "home#landing"
  get "admin_dash" => "home#admin_dash"
  get "faq" => "home#faq"
  get "about" => "home#about"
  get "privacy_policy" => "home#privacy_policy"
  get "terms_of_service" => "home#terms_of_service"
  root 'users#show'

  namespace :api do
    namespace :v1 do
      resources :users, only: [:show, :update, :create] do
        resources :groups, only: [:index]
        member do
          get 'personal_messages'
          post 'add_group'
        end
      end

      resources :groups, only: :show do
        delete 'drop_user', on: :member
        resources :activities, only: [:create, :update, :show] do
          member do
            post 'add_user'
            delete 'remove_user'
          end
        end
      end


      resources :messages, only: :create
      resources :sessions, only: [:create, :destroy]
    end
  end

  get "*any", via: :all, to: "errors#not_found"
end

app/models/user.rb
class User < ActiveRecord::Base
	extend FriendlyId
	include Sluggable
	include Tokenable
	friendly_id :slug_candidates, use: :slugged

	validates :longitude, :latitude, :address, :category, :age_group, presence: true, on: :update
	validates :terms_of_service, acceptance: true
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255}, format: { with: VALID_EMAIL_REGEX }, uniqueness: true
	validate :check_two_word_name, on: :update
	validate :password_complexity

	has_secure_password

	has_many :user_groups
	has_many :groups, through: :user_groups
	has_many :posted_messages, class_name: "Message", foreign_key: "poster_id", dependent: :destroy
	has_many :messages, as: :messageable, dependent: :destroy
	has_many :notifications, dependent: :destroy
	has_many :friends, through: :groups, source: :users
	has_many :user_activities
	has_many :activities, through: :user_activities, dependent: :destroy
	has_many :owned_activities, class_name: "Activity", foreign_key: "proposer_id", dependent: :destroy
	has_many :drop_user_votes, dependent: :destroy
	has_many :votes_to_drop, class_name: "DropUserVote", foreign_key: "voter_id", dependent: :destroy
	has_many :expand_group_votes, foreign_key: "voter_id", dependent: :destroy
	has_many :posted_notifications, class_name: "Notification", foreign_key: "poster_id", dependent: :destroy

	after_create { UserMailer.confirm_email(self).deliver_now if email_needs_verification?}
	after_update { find_group if sign_up_complete_changed? }
	before_update { self.sign_up_complete = true unless sign_up_complete? }
	before_create do
		generate_token(:auth_token)
		generate_token(:password_reset_token)
	end
	before_save :downcase_email

	after_validation :geocode
	reverse_geocoded_by :latitude, :longitude

	delegate :unviewed_notifications, :dismiss_personal_notifications_from_user, :unviewed_personal_notifications_from_user_count, :unviewed_group_notification_count, :dismiss_group_notifications_from_group, :unviewed_category_notifications, :dismiss_activity_notification, :unviewed_activity_notifications_count, :unviewed_activity_message_notifications_count, :unviewed_message_notifications_from_topic_count, :dismiss_topic_notifications_from_topic, :unviewed_activity_create_notifications_from_group, :poster_sorted_category_notifications, :unviewed_future_activity_notifications, :show_notifications_count, :show_notifications_positive?, to: :notifications
	delegate :group_drop_votes_count, :voter_vote, to: :drop_user_votes
	delegate :future_activities, to: :activities
	delegate :count, to: :groups, prefix: true
	delegate :degree_groups, to: :groups
	delegate :include?, :count, to: :unique_friends, prefix: true

	scope :users_by_slug, -> (slugs) { where(slug: slugs)  }

	def self.create_with_omniauth(auth)
		new_password = SecureRandom.hex(10)

		create! do |user|
			user.provider = auth.provider
			user.uid = auth.uid
			user.name = auth.info.name
			user.email = auth.info.email
			user.photo_url = auth.info.image
			user.password = new_password
			user.password_confirmation = new_password
		end
	end

	def unique_friends
		@unique_friends ||= friends.where.not(id: self).uniq
	end

	def can_unvote?(user)
		self != user && user.voter_vote(self) && self.unique_friends_include?(user)
	end

	def can_vote?(user)
		self != user && !user.voter_vote(self) && self.unique_friends_include?(user)
	end

	def under_group_limit?
	  groups_count < group_limit
	end

	def city
	  address.split(',')[1..-1].join(',')
	end

	def send_notification?(type)
	   notification_settings[type].nil? || notification_settings[type].to_bool
	end

	def find_group
	  FindGroup.new(self).find_or_create
	end

	def multiple_words?
	  name.split.count > 1
	end

	def email_needs_verification?
	  if email_verified?
			false
		elsif provider == "facebook" || provider == "email"
			true
		else
			false
		end
	end

	private
	def downcase_email
	  self.email = email.downcase
	end

	def check_two_word_name
	  unless multiple_words?
			errors.add(:name, "must include a first and last")
		end
	end

	def should_generate_new_friendly_id?
	  name_changed? || super
	end

	def password_complexity
	  CheckPasswordComplexityService.new(password, errors).password_errors if password
	end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApiController
  before_action :set_user, except: :create
  respond_to :json

  def show
    render json: @user
  end

  def create
    password_confirmation = user_params[:password]
    user = User.new(user_params.merge(password_confirmation: password_confirmation))
    if user.save
      render json: user, status: 201
    else
      render json: { errors: user.errors }, status: 422
    end
  end

  def personal_messages
    render json: { messages: Message.personal_messages(@user, current_user) }
  end

  def update
    if @user.update(user_params)
      render json: @user, status: 200
    else
      render json: { errors: @user.errors }, status: 422
    end
  end

  def add_group
    if @user.under_group_limit?
      group = FindGroup.new(@user).find_or_create
      render json: group
    else
      render json: { errors: "Group limit already reached" }, status: 422
    end
  end

  private
  def set_user
    @user = User.friendly.find(params[:id])
  end

  def user_params
		params.require(:user).permit(:name, :email, :address, :password, :password_confirmation, :street, :city, :state, :category, :age_group, :latitude, :longitude)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		password_confirmation = user_params[:password]
	  @user = User.new(user_params.merge(provider: "email", password_confirmation: password_confirmation))

		if @user.save
			log_in(@user)
			redirect_to verify_email_users_path
		else
			render :new
		end
	end

	def show
		@user_show = current_user
		return redirect_to get_started_path unless current_user
		return redirect_to complete_sign_up_users_path unless current_user.sign_up_complete?
	end

	def personal_messages
		user = User.friendly.find(params[:id])
		authorize! :personal_messages, user
		@user = UserPersonalMessageShow.new(user, current_user, params[:page])
	end

	def edit
		respond_to do |format|
		  format.html
		  format.js
		end
	end

	def complete_sign_up
		return redirect_to(verify_email_users_path) if current_user.email_needs_verification?
		authorize! :read, current_user
	end

	def verify_email
		return redirect_to root_path if current_user.sign_up_complete?
	end

	def email_confirmed
		@user = User.friendly.find(params[:id])

		if @user.password_reset_token == params[:code]
			log_in(@user)
			@user.update_column(:email_verified, true)
			redirect_to complete_sign_up_users_path, notice: "Thanks. Your email address has been confirmed. You can now finish signing up."
		else
			redirect_to root_path
		end
	end

	def update_email
	  if UpdateEmail.new(current_user, new_email_params[:email]).update
			redirect_to verify_email_users_path, notice: "We sent you an email."
		else
			render :verify_email
		end
	end

	def update
		sign_up_complete = current_user.sign_up_complete?

		if current_user.update(user_params)
			flash[:welcome] = current_user.sign_up_complete? != sign_up_complete
			redirect_to root_path
		elsif current_user.sign_up_complete?
			render :edit
		else
			render :complete_sign_up
		end
	end

	def join_group
	  if current_user.under_group_limit?
	  	new_group = FindGroup.new(current_user).find_or_create
			redirect_to group_path(new_group)
	  end
	end

	def destroy
		group = current_user.degree_groups(1).take
		current_user.destroy
		if group
			group.users_empty? ? group.destroy : Groups::GroupSpaceCheck.new(group, current_user).check_space
		end
		redirect_to new_survey_path(params: { email: current_user.email })
	end

	private
	def new_email_params
	  params.require(:user).permit(:email)
	end

	def user_params
		params.require(:user).permit(:name, :address, :email, :password, :category, :age_group, :latitude, :longitude, :sign_up_complete, notification_settings: [:proposal, :mention, :personal, :expand])
	end
end

app/views/users/_edit.html.erb
	<br>
	<%= link_to "Delete Account", user_path(current_user), data: {confirm: "Are you sure you want to delete your account?", text: "This cannot be undone. All account information and connections will be permanently destroyed."}, method: :delete, class: "btn red" %>

	<br><br>
		<%= form_for(current_user) do |f| %>
			<%= render 'shared/errors', object: current_user %>

			<div class="input-field">
 				<%= f.text_field :name, class: 'validate', required: true %>
 				<%= f.label :name %>
 			</div>

	    <div class="input-field tooltipped" data-position="top" data-tooltip="You will need to drop your old group if you move.">
				<%= f.text_field :address, placeholder: "", class: "active validate", required: true %>
				<%= f.label :address, "Home Address", data: { error: "Use Autocomplete"} %>
	    </div>

			<div class="input-field tooltipped" data-position="top" data-tooltip="You will need to drop your old group if you want to change types.">
				<%= f.select :age_group, age_groups, { disabled: "Select Age Group" }, require: true %>
			</div>

			<div class="tooltipped" data-position="top" data-tooltip="You will need to drop your old group if you want to change types.">
				People Type?
				<% categories.each_with_index do |category, index| %>
					<%= f.radio_button :category, category, id: "user_category_#{index}" %>
					<%= f.label "category_#{index}", category %>
				<% end %>
			</div>

			<h3>Notification Settings</h3>
			<%= f.fields_for :notification_settings do |p| %>
				<div class="switch">
					Group Mention Emails:
					<label>
						Off
						<%= p.check_box :mention, {checked: current_user.send_notification?("mention") }, "true", "false" %>
						<span class="lever"></span>
						On
					</label>
				</div>

				<div class="switch">
					Personal Emails:
					<label>
						Off
						<%= p.check_box :personal, {checked: current_user.send_notification?("personal") }, "true", "false" %>
						<span class="lever"></span>
						On
					</label>
				</div>

				<div class="switch">
					Activity Proposal Emails:
					<label>
						Off
						<%= p.check_box :proposal, {checked: current_user.send_notification?("proposal") }, "true", "false" %>
						<span class="lever"></span>
						On
					</label>
				</div>

				<div class="switch">
					Group Expansion Emails:
					<label>
						Off
						<%= p.check_box :expand, {checked: current_user.send_notification?("expand")}, "true", "false" %>
						<span class="lever"></span>
						On
					</label>
				</div>
			<% end %>

			<%= f.hidden_field :latitude, id: "lat" %>
			<%= f.hidden_field :longitude, id: 'lng' %>
			<br>
				<%= f.submit :Submit, class: 'btn blue' %>
	<% end %>

app/views/users/_friends.html.erb
<ul class="collection">
  <% unless friends.any? %>
  <h5></h5>
  <li class="collection-item no-users">You haven't been connected with anyone yet. We'll send you an email when your group is filled.</li>
  <% else %>
    <% friends.each do |friend| %>
      <li class='collection-item avatar'>
        <%= image_tag friend.photo_url || avatar_url(friend), class: "circle" %>
        <span class="title"><%= link_to friend.name, personal_messages_user_path(friend) %></span>
        <span class="secondary-content"><%= current_user.unviewed_personal_notifications_from_user_count(friend) %></span>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/users/_new.html.erb
<%= form_for @user do |f| %>
  <%= render 'shared/errors', object: @user %>

  <div class="input-field">
    <%= f.label :email %>
    <%= f.email_field :email, class: "validate", required: true %>
  </div>

  <div class="input-field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="input-field right-align">
    <%= f.submit "Sign up", class: "btn green signed-up" %>
  </div>
<% end %>

app/views/users/complete_sign_up.html.erb
<div class="container">
  <div class="card-panel">
    <h3>Complete Sign Up</h3>
    <%= form_for(current_user) do |f| %>
      <%= render 'shared/errors', object: current_user %>

      <div class="input-field">
        <%= f.label :name %>
        <%= f.text_field :name, class: "validate", required: true %>
      </div>

      <div class="input-field tooltipped" data-position="top" data-tooltip="We need to know exactly where you live. We'll never tell anyone.">
        <%= f.text_field :address, placeholder: "", required: true %>
        <%= f.label :address, "Home Address", data: { error: "Please select autocompleted address" } %>
      </div>

      <div class="input-field tooltipped" data-position="top" data-tooltip="No one's going to card you. Pick the group you identify with most.">
  			<%= f.select :age_group, age_groups, {disabled: "Select Age Group", selected: current_user.age_group || "Select Age Group"}, require: true %>
  		</div>

      <div id="people-type">
        People Type?
        <% categories.each_with_index do |category, index| %>
          <%= f.radio_button :category, category, id: "user_category_#{index}" %>
          <%= f.label "category_#{index}", category %>
        <% end %>
      </div>

      <p>
        <%= check_box_tag :terms_of_service, true, true %>
        <%= label_tag :terms_of_service, "I agree to the #{link_to "Terms of Service", terms_of_service_path}".html_safe %>
      </p>

      <%= f.hidden_field :latitude, id: "lat" %>
      <%= f.hidden_field :longitude, id: 'lng' %>

      <div class="modal-footer">
        <%= f.submit :Submit, class: 'btn blue' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <%= render "users/edit" %>
</div>

app/views/users/edit.js.erb
$(".modal-content").html("<%= j render partial: "edit" %>");

$('#edit-user').openModal();

app/views/users/edit_available_days.html.erb
<%= form_for @user do |f| %>
  <%= f.fields_for :available_days do |aday| %>
    <div class="column">
    <div class="box-row header">
    <%= aday.label weekdays[aday.options[:child_index]][0] %>
    <%= aday.hidden_field :day, value: weekdays[aday.options[:child_index]][1]  %>

    </div>

    <div class="box-row">
    <%= aday.label :morning %>
    <%= aday.check_box :morning %>

    </div>

    <div class="box-row">

    <%= aday.label :afternoon %>
    <%= aday.check_box :afternoon %>
    </div>

    <div class="box-row">

    <%= aday.label :evening %>
    <%= aday.check_box :evening %>
    </div>
    </div>
  <% end %>

  <br>
  <div class="box-button">
  <%= f.submit 'Submit', class: "btn btn-primary box-button" %>
  </div>
<% end %>

app/views/users/edit_excluded_days.html.erb
<%= form_for @user do |f| %>
  <%= f.fields_for :excluded_days do |eday| %>
    <div class="form-group">
      <div class="input-group date datepicker">
        <%= eday.text_field :excluded_date, placeholder: 'When? Hit button -->', class: 'form-control', required: true %>
        <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
      </div>
    <%= eday.label :morning %>
    <%= eday.check_box :morning %>

    <%= eday.label :afternoon %>
    <%= eday.check_box :afternoon %>

    <%= eday.label :evening %>
    <%= eday.check_box :evening %>
    <% end %>
    </div>
  <%= f.submit 'Submit', class: 'btn btn-primary' %>
<% end %>

<%= javascript_tag do %>
  $('.datepicker').datetimepicker({
    format: 'YYYY-MM-DD'
  });
<% end %>

app/views/users/new.html.erb
<div class="container">
  <div class="card-panel">
    <%= render 'users/new' %>
  </div>
</div>

app/views/users/new.js.erb
$(".modal-content").html("<%= j render partial: "new" %>");

app/views/users/personal_messages.html.erb
<div class="container">
	<div class="card-panel z-depth-2">
		<h2><%= @user.user_name %></h2>
		Location: <%= @user.user_city %> <br>
		Category: <%= @user.user_category %>
	</div>

	<% unless @user.own_profile? %>
		<%= render partial: 'messages/messages', locals: { messages: @user.messages, messageable: @user.user, new_message: @user.new_message} %>
<% end %>

</div>

app/views/users/personal_messages.js.erb
<%= render partial: 'messages/more_messages.js.erb', locals: { messages: @user.messages, next_page: @user.next_page } %>

app/views/users/public_profile.html.erb
<div class="container">
	<div class="card-panel z-depth-2">
		<h2><%= @user.user_name %></h2>
		Location: <%= @user.user_city %> <br>
		Category: <%= @user.user_category %>
	</div>

	<% unless @user.own_profile? %>
		<%= render partial: 'messages/messages', locals: { messages: @user.personal_messages, messageable: @user.user, new_message: @user.new_message} %>
<% end %>

</div>

app/views/users/show.html.erb
<div class="row">
	<div class="col m12">
	<h3><%= current_user.name %></h3>
		<span class="hide-on-med-and-down">
			<%= link_to "<i class='material-icons medium'>settings</i> Settings".html_safe, edit_user_path(current_user), class: "btn orange" %>
		</span>
		<%= link_to "Join Group", join_group_user_path(current_user), class: "btn green", method: :post if current_user.under_group_limit? %></h5>
	</div>

		<div class="col s12 l6">
		<h3>Groups</h3>
		<div class="collection">
			<% current_user.groups.each do |group| %>
				<%= link_to group_path(group), class: "collection-item" do %>
				<%= group.name %> <span class='badge'><%= current_user.unviewed_group_notification_count(group) %></span>
				<% end %>
			<% end %>
		</div>

		<div class="hide-on-med-and-down">
			<% if current_user.unique_friends.any? %>
				<h3>Friends</h3>
				<%= render partial: "users/friends", locals: { friends: current_user.unique_friends } %>
			<% end %>
		</div>
	</div>

	<div class="col s12 l6">
		<%= render partial: "activities/activities", locals: { activities: current_user.future_activities, group: current_user.groups.first, user_show: true } %>
	</div>
</div>

<div class="modal bottom-sheet" id="friends">
	<div class="modal-content">
		<h4>Friends</h4>
		<%= render partial: "users/friends", locals: { friends: current_user.unique_friends } %>
	</div>
</div>

<% if flash[:welcome] == true %>
	<%= render "shared/welcome", locals: { user: current_user } %>
<% end %>