config/routes.rb
Rails.application.routes.draw do
  resources :users, except: :index do
    resources :messages, only: :create

    collection do
      get 'complete_sign_up'
      get 'verify_email'
      patch 'update_email'
    end

    member do
      get 'email_confirmed'
      get 'personal_messages'
      post 'join_group'
    end
  end

  resources :groups, only: [:show] do
    delete 'drop_user', on: :member
    resources :drop_user_votes, only: [:create, :destroy]
    resources :expand_group_votes, only: [:create, :destroy]
    resources :topics, shallow: true, only: [:show, :create] do
      resources :messages, only: :create
      get 'change', on: :member
    end
    resources :activities, shallow: true, except: [:index] do
      resources :messages, only: [:create, :index]
      member do
        post 'add_user'
        delete 'remove_user'
      end
    end
  end

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/get_started')
  delete 'logout' => 'sessions#destroy'
  post 'login' => 'sessions#login'

  resources :password_resets, except: [:get, :destroy]
  resources :newsletters, only: [:new, :create]
  resources :surveys, only: [:new, :create]

  get "get_started" => "home#landing"
  get "admin_dash" => "home#admin_dash"
  get "faq" => "home#faq"
  get "about" => "home#about"
  get "privacy_policy" => "home#privacy_policy"
  get "terms_of_service" => "home#terms_of_service"
  root 'users#show'

  namespace :api do
    namespace :v1 do
      resources :users, only: [:show, :update, :create] do
        resources :groups, only: [:index]
        member do
          get 'personal_messages'
          post 'add_group'
        end
      end

      resources :groups, only: :show do
        delete 'drop_user', on: :member
        resources :activities, only: [:create, :update, :show] do
          member do
            post 'add_user'
            delete 'remove_user'
          end
        end
      end


      resources :messages, only: :create
      resources :sessions, only: [:create, :destroy]
    end
  end

  get "*any", via: :all, to: "errors#not_found"
end

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <% object.errors.full_messages.each do |msg| %>
    <div class="red-text error-messages"><%= msg %></div>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="page-footer">
	<div class="row center">
				<%= link_to "About", about_path, class: 'white-text' %>
				<%= link_to "Terms", terms_of_service_path, class: 'white-text' %>
				<%= link_to "Privacy", privacy_policy_path, class: 'white-text' %>

				<%= mail_to "support@gokrewe.com", "Contact", class: "white-text" %>
				<a target="_blank" class="white-text" href="https://twitter.com/gokrewe">Twitter</a>
				<a href="https://www.facebook.com/gokrewe/" target="_blank" class="white-text">Facebook</a>
				<a href="https://medium.com/@baronwilleford" target="_blank" class="white-text">Medium</a>

				<div class="brown-text text-lighten-3">Krewe Incorporated ©2016</div>
	</div>
</footer>

app/views/shared/_nav.html.erb
<nav>
	<div class="nav-wrapper">

		<a href="/" class="brand-logo">
			<%= image_tag 'krewe.png', id: 'logo' %>
		</a>
		<a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>

		<ul class="right hide-on-med-and-down">
			<% if current_user %>

				<li> <%= link_to "Home", root_path %></li>
				<% if current_user.try(:show_notifications_positive?) %>
					<li><a class="dropdown-button" href="#!" data-activates="note-alerts">Notifications<i class="material-icons right">arrow_drop_down</i></a></li>

					<ul id="note-alerts" class="dropdown-content">
						<li><%= render 'shared/notifications' %></li>
					</ul>
				<% end %>
				<li> <%=  link_to 'Log Out', logout_path, method: :delete %></li>
			<% else %>
				<li><a href="#login" class="modal-trigger">Log In</a></li>
			<% end %>

			<li><%= link_to "<i class='material-icons'>help</i>".html_safe, faq_path %></li>
		</ul>
	</div>
</nav>

<%= render "sessions/login" unless current_user %>

app/views/shared/_notifications.html.erb
<% current_user.poster_sorted_category_notifications("TopicMessage").each do |name, notifications| %>
  <li class="collection-item"><%= link_to "#{name} wrote in #{notifications.first.messageable_group.name} (#{notifications.count})", group_path(notifications.first.messageable_group) %></li>
<% end %>

<% current_user.poster_sorted_category_notifications("UserMessage").each do |name, notifications| %>
  <li class="collection-item"><%= link_to "#{name} sent you a message (#{notifications.count})", personal_messages_user_path(notifications.first.poster) %></li>
<% end %>

<% current_user.unviewed_category_notifications("Join").each do |notification| %>
  <li class="collection-item"><%= link_to "#{notification.poster_name} joined #{notification.notifiable.name}", group_path(notification.notifiable) %></li>
<% end %>

<% current_user.unviewed_future_activity_notifications("Activity").each do |notification| %>
  	<li class="collection-item"><%= link_to "#{notification.poster_name} proposed an activity: #{notification.notifiable_plan}", activity_path(notification.notifiable) %></li>
<% end %>

<% current_user.poster_sorted_category_notifications("ActivityMessage").each do |name, notifications| %>
  <li class="collection-item"><%= link_to "#{name} wrote in #{notifications.first.notifiable.messageable.plan} (#{notifications.count})", activity_path(notifications.first.notifiable.messageable) %></li>
<% end %>

<% current_user.unviewed_future_activity_notifications("ActivityUpdate").each do |notification| %>
  <li class="collection-item"><%= link_to  "#{notification.poster_name} made changes to #{notification.notifiable_plan}", activity_path(notification.notifiable) %></li>
<% end %>

app/views/shared/_sidebar.html.erb
<a href="#" data-activates="nav-mobile" class="button-collapse hide"><i class="material-icons">menu</i></a>

<ul id="nav-mobile" class="side-nav blue">
  <li><a href="/"><%= image_tag 'krewe.png', id: 'logo' %></a></li>

  <li><%= link_to "Home", root_path, class: 'white-text' %></li>

  <% if current_user %>
    <% if current_user.try(:show_notifications_positive?) %>
      <li><a href="#notifications" class="modal-trigger white-text">Notifications (<%= current_user.show_notifications_count %>)</a></li>
    <% end %>

    <% if @user_show %>
      <li><a href="#friends" class="modal-trigger white-text">Friends (<%= @user_show.unique_friends_count %>)</a></li>
      <li><%= link_to "Settings", edit_user_path(current_user), class: 'white-text' %></li>
      <li><%= link_to "FAQ", faq_path, class: 'white-text' %></li>
    <% end %>

    <% if @group_show %>
      <li><%= link_to "Propose Activity", new_group_activity_path(@group_show.group), class: 'white-text', id: 'new_activity' %></li>
      <li><a href="#activities" class="modal-trigger white-text">Upcoming Activities (<%= @group_show.activities_count %>)</a></li>
      <li><a href="#new-topic" class="modal-trigger white-text">New Thread</a></li>
      <li><a href="#members" class="modal-trigger white-text">Members (<%= @group_show.users_count %>)</a></li>

      <% if @group_show.ripe_for_expansion? %>
        <% unless @group_show.user_expand_group_votes(current_user) %>
          <li><%= link_to "Expand Group #{@group_show.expand_group_votes_size}/#{@group_show.users_count}", group_expand_group_votes_path(@group_show.group), method: :post, class: 'expand white-text', remote: @group_show.not_almost_expandable? %></li>
        <% else %>
          <li><%= link_to "Don't Expand #{@group_show.expand_group_votes_size}/#{@group_show.users_count}", group_expand_group_vote_path(@group_show.group, @group_show.user_expand_group_votes(current_user)), method: :delete, class: 'remain white-text', remote: true %></li>
        <% end %>
      <% end %>

      <li><%= link_to "Leave Group", drop_user_group_path(@group_show.group), class: 'white-text', method: :delete, data: {confirm: "Are you sure you want to drop this group?", text: "You will not be able to rejoin it.", 'confirm-button-text': "Yeah, these guys are jerks"} %></li>

    <% end %>

    <% if @activity_show %>
      <li><%= link_to "Messages #{@activity_show.note_count}", activity_messages_path(@activity_show.activity), class: 'white-text' %></li>
    <% end %>

    <li><%= link_to 'Log Out', logout_path, class: 'white-text', method: :delete %></li>
  <% else %>
    <li><a href="#login" class="white-text modal-trigger">Log In</a></li>
    <li><%= link_to "FAQ", faq_path, class: 'white-text' %></li>
  <% end %>
</ul>

<% if current_user.try(:show_notifications_positive?) %>
	<div id='notifications' class="modal">
		<div class="modal-content">
				<h3>Notifications</h3>
				<ul class="collection">
					<%= render 'shared/notifications' %>
				</ul>
		</div>
	</div>
<% end %>

app/views/shared/_welcome.html.erb
<div id="welcome-modal" class="modal modal-fixed-footer">
  <div class="modal-content">
    <h4>Welcome to Krewe</h4>
    <p>Thanks for signing up, this is how things here work:</p>
    <p>You've been placed in a group named <%= @user_show.groups.first.name %> that's limited to 6 people, all of whom live no more than a mile from you. Other users are placed in your group as soon as they sign up. No messing around with choosing people from their profiles and the superficial judgements that go along with that.</p>
    <p>Once your group is filled up, we highly recommend you set up an activity to meet up with them. You may not love everyone at first (who ever does?), but we think you'll find at least one person in your group you can get along with.</p>
    <p>Over time, and once you've become close with your group, you'll be able to expand and merge with other local groups. So, worse case scenario, you'll be able to make at least a few good friends. At best, you'll have a lot of really close friends in your neighborhood. It all depends on what you put into it.</p>
    <p>We're still new and working hard to get lots of users. If your group isn't full yet, it's ok. We'll email you when your group fills up.</p>
  </div>

  <div class="modal-footer">
    <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat">Ok, I got it</a>
  </div>
</div>