config/routes.rb
Rails.application.routes.draw do
  resources :users, except: :index do
    resources :messages, only: :create

    collection do
      get 'complete_sign_up'
      get 'verify_email'
      patch 'update_email'
    end

    member do
      get 'email_confirmed'
      get 'personal_messages'
      post 'join_group'
    end
  end

  resources :groups, only: [:show] do
    delete 'drop_user', on: :member
    resources :drop_user_votes, only: [:create, :destroy]
    resources :expand_group_votes, only: [:create, :destroy]
    resources :topics, shallow: true, only: [:show, :create] do
      resources :messages, only: :create
      get 'change', on: :member
    end
    resources :activities, shallow: true, except: [:index] do
      resources :messages, only: [:create, :index]
      member do
        post 'add_user'
        delete 'remove_user'
      end
    end
  end

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/get_started')
  delete 'logout' => 'sessions#destroy'
  post 'login' => 'sessions#login'

  resources :password_resets, except: [:get, :destroy]
  resources :newsletters, only: [:new, :create]
  resources :surveys, only: [:new, :create]

  get "get_started" => "home#landing"
  get "admin_dash" => "home#admin_dash"
  get "faq" => "home#faq"
  get "about" => "home#about"
  get "privacy_policy" => "home#privacy_policy"
  get "terms_of_service" => "home#terms_of_service"
  root 'users#show'

  namespace :api do
    namespace :v1 do
      resources :users, only: [:show, :update, :create] do
        resources :groups, only: [:index]
        member do
          get 'personal_messages'
          post 'add_group'
        end
      end

      resources :groups, only: :show do
        delete 'drop_user', on: :member
        resources :activities, only: [:create, :update, :show] do
          member do
            post 'add_user'
            delete 'remove_user'
          end
        end
      end


      resources :messages, only: :create
      resources :sessions, only: [:create, :destroy]
    end
  end

  get "*any", via: :all, to: "errors#not_found"
end

app/models/activity.rb
class Activity < ActiveRecord::Base
	belongs_to :group
	belongs_to :proposer, class_name: "User"
	has_many :user_activities
	has_many :users, through: :user_activities, after_add: :check_attendance, after_remove: :check_attendance
	has_many :notifications, as: :notifiable, dependent: :destroy
	has_many :messages, as: :messageable, dependent: :destroy

	reverse_geocoded_by :latitude, :longitude

	before_create :add_proposer_to_users
	after_create { ActivityNotification.new(self).send_notifications }
	after_update { ActivityNotification.new(self, "ActivityUpdate").send_notifications }

	validates :plan, presence: true, length: { minimum: 3 }
	validates_presence_of :location, :appointment, :group_id, :proposer_id
	validate :is_a_time?

	delegate :name, :users, :users_include?, to: :group, prefix: true
	delegate :size, to: :users, prefix: true

	scope :future_activities, -> { where('appointment > ?', Time.now - 2.hours).order(appointment: :asc) }
	scope :past_activities, -> { where('appointment < ?', Time.now) }
	scope :attended_activities, -> { past_activities.where( well_attended: true ) }
	scope :attended_activities_count, -> { attended_activities.size }

	def user_going?(user)
		users.include?(user)
	end

	def is_a_time?
		unless appointment.is_a?(Time)
			errors.add(:appointment, "must be a time")
		end
	end

	def check_attendance(user = nil)
		if users_size == 3 && self.well_attended != true
			self.well_attended = true
			save
		elsif users_size == 2 && self.well_attended != false
			self.well_attended = false
			save
		end
	end

	def proposed_by?(user)
		proposer == user
	end

	private
	def add_proposer_to_users
	  users << proposer
	end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
	def create
		authorize! :read, group
		@activity = group.activities.new(activity_params)

		if activity.save
			redirect_to activity_path(activity)
		else
			render :new
		end
	end

	def add_user
		authorize! :read, activity.group

		unless activity.user_going?(current_user)
			activity.users << current_user
			respond_to do |format|
				format.html { redirect_to activity_path(activity) }
				format.js
			end
		else
			redirect_to activity_path(activity)
		end
	end

	def remove_user
		authorize! :read, activity.group
		activity.users.delete(current_user)
		activity.check_attendance
		redirect_to current_user
	end

	def edit
		authorize! :update, activity
		@activity = activity
	end

	def update
		authorize! :update, activity
		if activity.update(activity_params)
			redirect_to activity_path(activity)
		else
			redirect_to edit_activity_path(activity), flash: { errors: activity.errors.full_messages }
		end
	end

	def show
		authorize! :read, activity.group
		@activity_show = ActivityShow.new({activity: activity, user: current_user, page: params[:page]})
	end

	def new
		authorize! :read, group
		@activity = Activity.new
	end

	def destroy
	  authorize! :update, activity

		activity.destroy
		redirect_to current_user
	end

	private
	def activity
		@activity ||= Activity.find(params[:id])
	end

	def group
		@group ||= Group.friendly.find(params[:group_id])
	end

	def activity_params
		params.require(:activity).permit(:plan, :appointment, :location, :latitude, :longitude).merge(proposer_id: current_user.id)
	end
end

app/controllers/api/v1/activities_controller.rb
class Api::V1::ActivitiesController < ApiController
  before_action :set_activity, except: :create
  before_action :authenticate_with_token!, only: [:create, :update]
  before_action :set_group, only: :create

  def show
    render json: @activity
  end

  def create
    activity = @group.activities.new(activity_params)

    if activity.save
      render json: activity, status: 201
    else
      render json: { errors: activity.errors }, status: 422
    end
  end

  def update
    if @activity.update(activity_params)
      render json: @activity, status: 200
    else
      render json: { errors: @activity.errors }, status: 422
    end
  end

  def add_user
    @activity.users << current_user

    render json: @activity, status: 201
  end

  def remove_user
    @activity.users.delete(current_user)

    head 204
  end

  private
  def set_activity
    @activity = Activity.find(params[:id])
  end

  def set_group
    @group = Group.friendly.find(params[:group_id])
  end

  def activity_params
    params.require(:activity).permit(:plan, :proposer_id, :group_id, :appointment, :location, :latitude, :longitude)
  end
end

app/views/activities/_activities.html.erb
<h4>Activities</h4>

<% if activities.any? %>
      <% activities.each do |activity| %>
      <div class="card">
        <div class="card-content">
          <span class="card-title"><%= link_to activity.plan, activity_path(activity) %></span>
          <p>
            <%= activity.location %>
            <%= local_time(activity.appointment) %>
            <span class='badge'><%= current_user.unviewed_activity_notifications_count(activity) %></span>
          </p>
        </div>
        <% unless user_show || activity.user_going?(current_user) %>
          <div class="card-action">
            <%= link_to "Go", add_user_activity_path(activity), method: :post, class: 'btn green waves-effect waves-light' %>
          </div>
        <% end %>
      </div>
      <% end %>
<% else %>
  <div class="card">
    <div class="card-content ">
      <span class="card-title black-text">No Upcoming Activities</span>
      <p>
        <%= link_to "Propose one...", new_group_activity_path(group) if group %>
      </p>
    </div>
  </div>
<% end %>

app/views/activities/_form.html.erb
<%= form_for([@group, @activity]) do |f| %>
  <%= render 'shared/errors', object: @activity %>

  <div id="map-canvas" data-longitude="<%= @group.longitude %>" data-latitude="<%= @group.latitude %>"></div><br>

  <div class="row">
    <div class="col s12 m6">

      <div class="row">
        <ul class="tabs">
          <li class="tab col s2"><a href="#" class="active place-type" data-type='bar' data-plan='Get drinks'><i class="material-icons">local_bar</i></a></li>
          <li class="tab col s2"><a href="#" class="place-type" data-type='restaurant' data-plan='Get food'><i class="material-icons">local_dining</i></a></li>
          <li class="tab col s2"><a href="#" class="place-type" data-type='cafe' data-plan='Get coffee'><i class="material-icons">local_cafe</i></a></li>
        </ul>
      </div>

      <ul class="collection" id="spots">
        <li class="collection-item">Some places nearby...</li>
      </ul>
    </div>

    <div class="col s12 m6">
      <div class="input-field">
        <%= f.text_field :plan, required: true %>
        <%= f.label :plan, "What's the plan?" %>
      </div>
      <div class="input-field">
        <%= f.text_field :location, placeholder: "", required: true %>
        <%= f.label :location, "Where?" %>
      </div>

      <div class="input-field">
        <%= text_field_tag :day, "", class: "datepicker", id: "date_field", required: true %>
        <%= label_tag :date_field, "What day?" %>
      </div>

      <div class="input-field">
        <%= text_field_tag :time, "", id: "time_field", required: true %>
        <%= label_tag :time_field, "What time?" %>
      </div>

        <%= f.hidden_field :appointment %>
    </div>

    <%= f.hidden_field :longitude %>
    <%= f.hidden_field :latitude %>

    <div class="right-align">
      <%= f.submit "Submit", class: 'btn green' %>
    </div>
  </div>
<% end %>

app/views/activities/_new.html.erb
<div class="modal-content">
	<%= render 'activities/form' %>
</div>

app/views/activities/add_user.js.erb
$("#activity-go").replaceWith('<%= link_to "Can't go", remove_user_activity_path(@activity), method: :delete, class: 'btn red' %>')

app/views/activities/edit.html.erb
<div class="container">
  <div class="card-panel">
    <%= form_for(@activity) do |f| %>
      <%= render 'shared/errors', object: @activity %>

      <div class="row">
        <div class="col s12 m6">

          <div class="row">
            <ul class="tabs">
              <li class="tab col s2"><a href="#" class="active place-type" data-type='bar' data-plan='Get drinks'><i class="material-icons">local_bar</i></a></li>
              <li class="tab col s2"><a href="#" class="place-type" data-type='restaurant' data-plan='Get food'><i class="material-icons">local_dining</i></a></li>
              <li class="tab col s2"><a href="#" class="place-type" data-type='cafe' data-plan='Get coffee'><i class="material-icons">local_cafe</i></a></li>
            </ul>
          </div>

          <ul class="collection" id="spots">
            <li class="collection-item">Some places nearby...</li>
          </ul>
        </div>

        <div class="col s12 m6">
          <div class="input-field">
            <%= f.text_field :plan, class: "validate", required: true %>
            <%= f.label :plan, "What's the plan?" %>
          </div>
          <div class="input-field">
            <%= f.text_field :location, placeholder: "",class: "validate", required: true %>
            <%= f.label :location, "Where?" %>
          </div>

          <div class="input-field">
            <%= text_field_tag :day, @activity.appointment.to_date, class: "datepicker", id: "date_field", required: true %>
            <%= label_tag :date_field, "What day?" %>
          </div>

          <div class="input-field">
            <%= text_field_tag :time, @activity.appointment.to_time, id: "time_field", required: true %>
            <%= label_tag :time_field, "What time?" %>
          </div>

            <%= f.hidden_field :appointment %>
        </div>

        <%= f.hidden_field :longitude %>
        <%= f.hidden_field :latitude %>
        <div id="map-canvas" data-latitude="<%= @activity.latitude %>" data-longitude="<%= @activity.longitude %>"></div>

        <div class="modal-footer">
          <%= f.submit "Submit", class: 'btn green' %>
        </div>
      </div>
    <% end %>
</div>

app/views/activities/new.html.erb
<div class="container">
  <div class="card-panel">
    <h4>Propose Activity for <%= link_to @group.name, group_path(@group) %></h4>
    <%= render 'activities/form' %>
  </div>
</div>

app/views/activities/new.js.erb
$('#new-activity').html("<%= j render partial: "new" %>")

$('#new-activity').openModal();

Activity.activitySetup();
$(document).on('click', '.suggested', GooglePlaces.selectSuggested);
$(document).on('click', '.place-type', GooglePlaces.selectMarked);

app/views/activities/show.html.erb
<div class="row container">
	<div class="col s12 card-panel z-depth-2">
		<h3><%= @activity_show.plan %></h3>
		<% if @activity_show.user_going?(current_user) %>
			<%= link_to "Can't go", remove_user_activity_path(@activity_show.activity), method: :delete, class: 'btn red waves-effect waves-light' %>
		<% else %>
			<%= link_to "Go", add_user_activity_path(@activity_show.activity), remote: true, method: :post, class: 'btn green waves-effect waves-light', id: "activity-go" %>
		<% end %>
		<% if @activity_show.proposed_by?(current_user) %>
			<%= link_to "Edit Activity", edit_activity_path(@activity_show.activity), class: 'btn orange waves-effect waves-light' %>
			<%= link_to "Delete Activity", activity_path(@activity_show.activity), method: :delete, class: "btn red white-text", data: {confirm: "Are you sure you want to delete this activity?"} %>
		<% end %>
		<button type="button" class="btn light-green waves-effect waves-light right-align" id="map-hider" >Toggle Map</button>
		<h3><%= link_to @activity_show.group_name, @activity_show.group %></h3>
		<h4><%= local_time(@activity_show.appointment) %></h4>
		<h4><%= @activity_show.location %></h4>

		<div id="map-canvas" data-latitude="<%= @activity_show.latitude %>" data-longitude="<%= @activity_show.longitude %>"></div>
	</div>

	<div class="col l6 m12 s12">
		<h3>People going</h3>
			<ul class="collection">
			<% @activity_show.users.each do |user| %>
				<%= link_to user.name, personal_messages_user_path(user), class: "collection-item" %>
			<% end %>
			</ul>
	</div>

	<div class="col l6 hide-on-med-and-down" id="activity-messages">
		<h3>Messages</h3>
		<%= render partial: "messages/messages", locals: { messages: @activity_show.messages, messageable: @activity_show.activity, new_message: @activity_show.new_message } %>
	</div>
</div>

app/views/activities/show.js.erb
<%= render partial: 'messages/more_messages.js.erb', locals: { messages: @activity_show.messages, next_page: @activity_show.next_page } %>